name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 1.0.5
homepage: https://github.com/QasimWaheed/google_maps_webservice

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  http: ^1.2.2
  meta: ^1.16.0
  json_annotation: ^4.9.0
  lints: ^4.0.0

dev_dependencies:
  test: ^1.25.8
#  pedantic: ^1.11.1
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  coverage: ^1.9.2
